version: '2'

services:
    crossdock:
        image: crossdock/crossdock
        links:
            - test_driver
            - go
            - java-udp
            - java-http
            - java-https
            - python
            - nodejs
        environment:
            - WAIT_FOR=test_driver,go,java-udp,java-http,java-https,python,nodejs
            - WAIT_FOR_TIMEOUT=60s

            - CALL_TIMEOUT=60s

            - AXIS_CLIENT=go
            - AXIS_S1NAME=go,java-udp,python,nodejs
            - AXIS_SAMPLED=true,false
            - AXIS_S2NAME=go,java-udp,python,nodejs
            - AXIS_S2TRANSPORT=http
            - AXIS_S3NAME=go,java-udp,python,nodejs
            - AXIS_S3TRANSPORT=http

            - BEHAVIOR_TRACE=client,s1name,sampled,s2name,s2transport,s3name,s3transport

            - AXIS_TESTDRIVER=test_driver
            - AXIS_SERVICES=java-udp,java-http,java-https

            - BEHAVIOR_ENDTOEND=testdriver,services

            - REPORT=compact

    go:
        image: jaegertracing/xdock-go
        ports:
            - "8080-8082"

    python:
        image: jaegertracing/xdock-py
        ports:
            - "8080-8082"

    nodejs:
        image: jaegertracing/xdock-node
        ports:
            - "8080-8082"

    java-udp:
        depends_on:
            - test_driver
        build: .
        ports:
            - "8080-8082"
        environment:
            - SENDER=udp

    java-http:
        build: .
        ports:
            - "8080-8082"
        environment:
            - SENDER=http

    java-https:
        build: .
        ports:
            - "8080-8082"
        environment:
            - SENDER=https
        depends_on:
            - jaeger-collector

    jaeger-collector-https-proxy:
        image: nginx
        ports:
            - "14443:14443"
        volumes:
            - ./https-proxy/build/proxy.conf:/etc/nginx/conf.d/proxy.conf
            - ./https-proxy/build/proxy.crt:/etc/nginx/proxy.crt
            - ./https-proxy/build/proxy.key:/etc/nginx/proxy.key
        depends_on:
            - jaeger-collector
        command: ["nginx", "-g", "daemon off;"]

    test_driver:
        image: jaegertracing/test-driver
        depends_on:
            - jaeger-query
            - jaeger-collector
            - jaeger-agent
            - jaeger-collector-https-proxy
        ports:
            - "8080"
